[package]
name = "comp_4555_term_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.0"
log = "0.4.17"
ron = "0.8.0"
serde = "1.0.147"
